# This is a basic workflow to help you get started with Actions

name: CRON

on:
  # cron
  schedule:
    - cron: '0 0,3,6,9,12,15,18,21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  cron_key: ${{ secrets.CRON_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CRON:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      - name: echo
        run: echo ${env.cron_key:0:6}
      - name: CURL
        run: curl -XGET https://httpbin.org/get?key=${{ env.cron_key }} -H "User-Agent:NNJZML/CRON:siejru"
