# This is a basic workflow to help you get started with Actions

name: CRON

on:
  # cron
  #schedule:
    #- cron: '0 0,3,6,9,12,15,18,21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  cron_key: ${{ secrets.CRON_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CRON:
    runs-on: ubuntu-latest
    steps:
      - name: CURL
        run: curl -XGET https://guide.nnjz.ml/api/admin/cron?key=${{ env.cron_key }} -H "User-Agent:NNJZML/CRON:${{ env.cron_key }}"
